version: '3.9'

services:
  firewall:
    build: ./firewall-gw
    container_name: firewall-gw
    privileged: true
    networks:
      guest_net:
        ipv4_address: 10.10.1.254
      mgmt_net:
        ipv4_address: 10.10.2.254
      eth_net:
        ipv4_address: 10.10.3.254
    cap_add:
      - NET_ADMIN

  guest1:
    image: alpine
    container_name: guest1
    command: sh -c "apk add iputils && sleep infinity"
    networks:
      guest_net:
        ipv4_address: 10.10.1.11
    volumes:
      - ./init-routes.sh:/init-routes.sh

  guest2:
    image: alpine
    container_name: guest2
    command: sh -c "apk add iputils && sleep infinity"
    networks:
      guest_net:
        ipv4_address: 10.10.1.12
    volumes:
      - ./init-routes.sh:/init-routes.sh

  mgmt1:
    image: alpine
    container_name: mgmt1
    command: sh -c "apk add iputils libcap && sh /init-routes.sh && sleep infinity"
    networks:
      mgmt_net:
        ipv4_address: 10.10.2.11
    volumes:
      - ./init-routes.sh:/init-routes.sh
    cap_add:
      - NET_ADMIN

  mgmt2:
    image: alpine
    container_name: mgmt2
    command: sh -c "apk add iputils libcap && sh /init-routes.sh && sleep infinity"
    networks:
      mgmt_net:
        ipv4_address: 10.10.2.12
    volumes:
      - ./init-routes.sh:/init-routes.sh
    cap_add:
      - NET_ADMIN

  eth1:
    image: alpine
    container_name: eth1
    command: sh -c "apk add iputils libcap && sh /init-routes.sh && sleep infinity"
    networks:
      eth_net:
        ipv4_address: 10.10.3.11
    volumes:
      - ./init-routes.sh:/init-routes.sh
    cap_add:
      - NET_ADMIN

  eth2:
    image: alpine
    container_name: eth2
    command: sh -c "apk add iputils libcap && sh /init-routes.sh && sleep infinity"
    networks:
      eth_net:
        ipv4_address: 10.10.3.12
    volumes:
      - ./init-routes.sh:/init-routes.sh
    cap_add:
      - NET_ADMIN

  core-server:
    image: nginx:alpine
    container_name: core-server
    networks:
      guest_net:
        ipv4_address: 10.10.1.100
      mgmt_net:
        ipv4_address: 10.10.2.100
      eth_net:
        ipv4_address: 10.10.3.100

networks:
  guest_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.1.0/24
  mgmt_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.2.0/24
  eth_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.3.0/24